package jss;

/**
 * Interface for objects that trigger events in the @see Simulator.
 *
 * As the simulation starts to run, the Simulator will start querying the
 * @see IProblemInstance to retrieve and queue up the events generated by
 * the event handlers by the order of the event trigger times. The
 * IEventHandler, therefore, has the responsibility of representing future
 * events associated with the IEventHandler as an instance of @see IEvent.
 *
 * @author parkjohn
 *
 */
public interface IEventHandler {

	/**
	 * Returns whether the object has events or not.
	 * @return false if no more events are to be triggered by the object.
	 */
	public boolean hasEvent();

	/**
	 * Returns the next event to be queued up by the Simulator.
	 * @return null if no more events are to be triggered by the object.
	 */
	public IEvent getNextEvent();

	/**
	 * Returns the time when the next event is triggered at.
	 * @return infinity of no more events are to be triggered by the object.
	 */
	public double getNextEventTime();
}
