package jss;

import java.util.List;

/**
 * Represents a solution generated by the @see ISolver for a particular job
 * shop scheduling problem instance.
 *
 * @author parkjohn
 *
 */
public interface IResult {

	/**
	 * Add an action that the solution generator takes for solving the job
	 * shop scheduling problem instance.
	 * @param action The action taken by the solver.
	 */
	public void addAction(Action action);

	/**
	 * Get the full list of actions that the solution generator took to solve
	 * the job shop scheduling problem instance.
	 * @return The solution as a list of action.
	 */
	public List<Action> getActions();

	/**
	 * Get the makespan of the solution.
	 * Makespan is defined as the latest completion time of all operations on
	 * the job shop scheduling environment.
	 * @return The makespan of the solution.
	 */
	public double getMakespan();

	/**
	 * Get the total weighted tardiness of the solution.
	 * Total weighted tardiness is defined as the sum of the weight multiplied
	 * by the tardiness of the operation, which is the positive difference
	 * between the completion time and the due date of the operation.
	 * @return The total weighted tardiness of the solution.
	 */
	public double getTWT();
}
